const Map<String, String> countryFlags = {
  "italy": "🇮🇹",
  "italia": "🇮🇹",
  "france": "🇫🇷",
  "francia": "🇫🇷",
  "spain": "🇪🇸",
  "spagna": "🇪🇸",
  "germany": "🇩🇪",
  "germania": "🇩🇪",
  "portugal": "🇵🇹",
  "portogallo": "🇵🇹",
  "united states": "🇺🇸",
  "stati uniti": "🇺🇸",
  "usa": "🇺🇸",
  "united kingdom": "🇬🇧",
  "regno unito": "🇬🇧",
  "uk": "🇬🇧",
  "canada": "🇨🇦",
  "mexico": "🇲🇽",
  "messico": "🇲🇽",
  "brazil": "🇧🇷",
  "brasile": "🇧🇷",
  "argentina": "🇦🇷",
  "colombia": "🇨🇴",
  "peru": "🇵🇪",
  "venezuela": "🇻🇪",
  "chile": "🇨🇱",
  "australia": "🇦🇺",
  "new zealand": "🇳🇿",
  "nuova zelanda": "🇳🇿",
  "japan": "🇯🇵",
  "giappone": "🇯🇵",
  "china": "🇨🇳",
  "cina": "🇨🇳",
  "south korea": "🇰🇷",
  "corea del sud": "🇰🇷",
  "north korea": "🇰🇵",
  "corea del nord": "🇰🇵",
  "india": "🇮🇳",
  "pakistan": "🇵🇰",
  "bangladesh": "🇧🇩",
  "russia": "🇷🇺",
  "ukraine": "🇺🇦",
  "ucraina": "🇺🇦",
  "poland": "🇵🇱",
  "polonia": "🇵🇱",
  "sweden": "🇸🇪",
  "svezia": "🇸🇪",
  "norway": "🇳🇴",
  "norvegia": "🇳🇴",
  "finland": "🇫🇮",
  "finlandia": "🇫🇮",
  "denmark": "🇩🇰",
  "danimarca": "🇩🇰",
  "netherlands": "🇳🇱",
  "olanda": "🇳🇱",
  "belgium": "🇧🇪",
  "belgio": "🇧🇪",
  "switzerland": "🇨🇭",
  "svizzera": "🇨🇭",
  "austria": "🇦🇹",
  "greece": "🇬🇷",
  "grecia": "🇬🇷",
  "turkey": "🇹🇷",
  "turchia": "🇹🇷",
  "israel": "🇮🇱",
  "israele": "🇮🇱",
  "saudi arabia": "🇸🇦",
  "arabia saudita": "🇸🇦",
  "uae": "🇦🇪",
  "qatar": "🇶🇦",
  "egypt": "🇪🇬",
  "egitto": "🇪🇬",
  "south africa": "🇿🇦",
  "sudafrica": "🇿🇦",
  "morocco": "🇲🇦",
  "marocco": "🇲🇦",
  "tunisia": "🇹🇳",
  "algeria": "🇩🇿",
  "nigeria": "🇳🇬",
  "kenya": "🇰🇪",
  "ethiopia": "🇪🇹",
  "etiopia": "🇪🇹",
  "thailand": "🇹🇭",
  "thailandia": "🇹🇭",
  "vietnam": "🇻🇳",
  "philippines": "🇵🇭",
  "filippine": "🇵🇭",
  "indonesia": "🇮🇩",
  "malaysia": "🇲🇾",
  "malesia": "🇲🇾",
  "singapore": "🇸🇬",
  "hong kong": "🇭🇰",
  "taiwan": "🇹🇼",
};
