final List<String> razzeGatti = [
  'Abissino',
  'American Bobtail',
  'American Curl',
  'American Shorthair',
  'American Wirehair',
  'Angora Turco',
  'Arabian Mau',
  'Australian Mist',
  'Balinese',
  'Bambino',
  'Bengala',
  'Birmano',
  'Blu di Russia',
  'Bombay',
  'British Longhair',
  'British Shorthair',
  'Burmese',
  'Burmilla',
  'California Spangled',
  'Chantilly-Tiffany',
  'Chartreux',
  'Chausie',
  'Colorpoint Shorthair',
  'Cornish Rex',
  'Cymric',
  'Devon Rex',
  'Don Sphynx (Donskoy)',
  'Dragon Li',
  'Egyptian Mau',
  'European Shorthair',
  'Exotic Shorthair',
  'German Rex',
  'Havana Brown',
  'Highlander',
  'Himalayano',
  'Japanese Bobtail',
  'Javanese',
  'Khao Manee',
  'Korat',
  'Kurilian Bobtail',
  'LaPerm',
  'Lykoi',
  'Maine Coon',
  'Manx',
  'Munchkin',
  'Napoleon',
  'Nebelung',
  'Norvegese delle Foreste',
  'Ocicat',
  'Orientale',
  'Persiano',
  'Peterbald',
  'Pixie-bob',
  'Ragamuffin',
  'Ragdoll',
  'Savannah',
  'Scottish Fold',
  'Selkirk Rex',
  'Serengeti',
  'Siamese',
  'Siberiano',
  'Singapura',
  'Snowshoe',
  'Sokoke',
  'Somalo',
  'Sphynx',
  'Thai',
  'Tiffanie',
  'Tonkinese',
  'Toyger',
  'Turkish Van',
  'Turkish Angora',
  'Ural Rex',
  'York Chocolate',
];