final List<String> razzeCavalli = [
  'Abtenauer',
  'Aegidienberger',
  'Akhal-Teke',
  'Albanese',
  'Altai',
  'Alter Real',
  'American Bashkir Curly',
  'American Cream Draft',
  'American Miniature Horse',
  'American Paint Horse',
  'American Quarter Horse',
  'American Saddlebred',
  'American Standardbred',
  'American Warmblood',
  'Andaluso',
  'Andravida',
  'Anglo-Arabo',
  'Anglo-Kabarda',
  'Appaloosa',
  'Arabo',
  'Ardennese',
  'Arenberg-Nordkirchen',
  'Asturcón',
  'Australian Draught',
  'Australian Pony',
  'Australian Stock Horse',
  'Austrian Warmblood',
  'Auxois',
  'Azteca',
  'Bardigiano',
  'Barb',
  'Bashkir',
  'Basuto',
  'Belgian Draft',
  'Belgian Warmblood',
  'Black Forest Horse',
  'Boerperd',
  'Bosnian Mountain Horse',
  'Brandenburger',
  'Breton',
  'British Warmblood',
  'Budyonny',
  'Camargue',
  'Campolina',
  'Canadian Horse',
  'Caspian',
  'Cleveland Bay',
  'Clydesdale',
  'Comtois',
  'Connemara Pony',
  'Criollo',
  'Curly Horse',
  'Dales Pony',
  'Dartmoor Pony',
  'Dutch Harness Horse',
  'Dutch Warmblood',
  'Eriskay Pony',
  'Exmoor Pony',
  'Falabella',
  'Fell Pony',
  'Finnhorse',
  'Fjord',
  'Frisone',
  'Galiceno',
  'Gelderlander',
  'Gypsy Vanner',
  'Hackney',
  'Haflinger',
  'Hanoverian',
  'Highland Pony',
  'Holsteiner',
  'Hucul',
  'Icelandic Horse',
  'Irish Draught',
  'Irish Sport Horse',
  'Jutland',
  'Karabair',
  'Karabakh',
  'Kazakh Horse',
  'Kladruber',
  'Knabstrupper',
  'Konik',
  'Kustanair',
  'Lipizzano',
  'Lusitano',
  'Malopolski',
  'Marwari',
  'Mecklenburger',
  'Merens',
  'Missouri Fox Trotter',
  'Mongolian Horse',
  'Morgan',
  'Murgese',
  'Mustang',
  'Nonius',
  'Noriker',
  'Oldenburg',
  'Orlov Trotter',
  'Paso Fino',
  'Percheron',
  'Peruvian Paso',
  'Pinto',
  'Poitevin',
  'Quarter Horse',
];