final List<String> razzeCani = [
  'Labrador Retriever',
  'Golden Retriever',
  'Pastore Tedesco',
  'Barboncino',
  'Bulldog Francese',
  'Bulldog Inglese',
  'Beagle',
  'Chihuahua',
  'Rottweiler',
  'Carlino',
  'Dobermann',
  'Border Collie',
  'Bassotto',
  'Shih Tzu',
  'Cocker Spaniel',
  'Maltese',
  'Husky Siberiano',
  'Alano',
  'Akita Inu',
  'Jack Russell Terrier',
  'Yorkshire Terrier',
  'Boxer',
  'Cavalier King Charles Spaniel',
  'Dalmata',
  'Boston Terrier',
  'Pinscher',
  'Shar Pei',
  'Bichon Frisé',
  'Setter Irlandese',
  'Weimaraner',
  'Schnauzer',
  'Levriero Afgano',
  'Barbone Toy',
  'Samoiedo',
  'Shiba Inu',
  'Cane Corso',
  'Pastore Maremmano',
  'Bull Terrier',
  'Australian Shepherd',
  'Basenji',
  'Terranova',
  'Whippet',
  'Pechinese',
  'Lhasa Apso',
  'Bovaro del Bernese',
  'Cane da Montagna dei Pirenei',
  'Komondor',
  'Kuvasz',
  'Mastino Napoletano',
  'Mastino Tibetano',
  'Cane Lupo Cecoslovacco',
  'Cane da Pastore Belga',
  'Cane da Pastore Scozzese',
  'Cane da Pastore Australiano',
  'Cane da Orso della Carelia',
  'Cane da Pastore Bergamasco',
  'Cane da Pastore Catalano',
  'Cane da Pastore dei Pirenei',
  'Cane da Pastore Olandese',
  'Cane da Pastore Tedesco a Pelo Lungo',
  'Cane da Pastore Ungherese Puli',
  'Cane da Pastore di Shetland',
  'Cane da Pastore Finlandese',
  'Cane da Pastore Polacco',
  'Cane da Pastore Scozzese a Pelo Corto',
  'Cane da Pastore di Brie (Briard)',
  'Cane da Pastore di Piccardia',
  'Cane da Pastore di Tatra',
  'Cane da Pastore di Vallée',
  'Cane da Pastore di Beauce',
  'Cane da Pastore di Anatolia',
  'Cane da Pastore di Ciarplanina',
  'Cane da Pastore di Karst',
  'Cane da Pastore di Maremma e Abruzzo',
  'Cane da Pastore di Russia Meridionale',
  'Cane da Pastore di Tatra',
  'Cane da Pastore Scozzese',
  'Cane da Pastore Tedesco',
  'Cane da Pastore Belga Groenendael',
  'Cane da Pastore Belga Laekenois',
  'Cane da Pastore Belga Malinois',
  'Cane da Pastore Belga Tervueren',
  'Cane da Pastore Catalano',
  'Cane da Pastore dei Pirenei a Pelo Lungo',
  'Cane da Pastore dei Pirenei a Pelo Corto',
  'Cane da Pastore Finlandese',
  'Cane da Pastore Islandese',
  'Cane da Pastore Norvegese',
  'Cane da Pastore Scozzese a Pelo Lungo',
  'Cane da Pastore Scozzese a Pelo Corto',
  'Cane da Pastore Tedesco',
  'Cane da Pastore Ungherese Komondor',
  'Cane da Pastore Ungherese Puli',
  'Cane da Pastore Ungherese Pumi',
  'Cane da Pastore di Brie',
  'Cane da Pastore di Piccardia',
  'Cane da Pastore di Vallée',
  'Cane da Pastore di Beauce',
  'Cane da Pastore di Anatolia',
  'Cane da Pastore di Ciarplanina',
  'Cane da Pastore di Karst',
  'Cane da Pastore di Russia Meridionale',
  'Cane da Montagna dei Pirenei',
  'Cane Lupo Cecoslovacco',
  'Cane Lupo Italiano',
  'Cane da Orso della Carelia',
  'Cane da Pastore Scozzese',
];