final List<String> razzeCriceti = [
  'Criceto Dorato (Siriano)',
  'Criceto Russo (Winter White)',
  'Criceto di Campbell',
  'Criceto di Roborovski',
  'Criceto Cinese',
  'Criceto Siriano a pelo corto',
  'Criceto Siriano a pelo lungo (Teddy Bear)',
  'Criceto Russo zaffiro',
  'Criceto Russo perla',
  'Criceto Russo blu',
  'Criceto Campbell albino',
  'Criceto Campbell agouti',
  'Criceto Campbell nero',
  'Criceto Roborovski faccia bianca',
  'Criceto Roborovski agouti',
  'Criceto Cinese normale',
  'Criceto Cinese bianco',
  'Criceto Siriano nero',
  'Criceto Siriano crema',
  'Criceto Siriano cannella',
  'Criceto Siriano satinato',
  'Criceto Siriano pezzato',
  'Criceto Siriano dorato classico',
  'Criceto Siriano argentato',
  'Criceto Siriano nero focato',
  'Criceto Siriano chocolate',
  'Criceto Siriano albino',
  'Criceto Siriano grigio',
  'Criceto Siriano tartarugato',
  'Criceto Siriano panda',
];