final List<String> razzeConigli = [
  'Alaska',
  'Altex',
  'American',
  'American Chinchilla',
  'American Fuzzy Lop',
  'American Sable',
  'Angora Inglese',
  'Angora Francese',
  'Angora Gigante',
  'Angora Satin',
  'Argente Bleu',
  'Argente Brun',
  'Argente Clair',
  'Argente Crème',
  'Argente de Champagne',
  'Argente Noir',
  'Belgian Hare',
  'Beveren',
  'Blanc de Hotot',
  'Blanc de Termonde',
  'Blue of Sint-Niklaas',
  'British Giant',
  'Britannia Petite',
  'Californian',
  'Cashmere Lop',
  'Checkered Giant',
  'Chinchilla Gigante',
  'Chinchilla Standard',
  'Cinnamon',
  'Continental Giant',
  'Czech Red',
  'Dwarf Hotot',
  'Dwarf Lop',
  'Dutch',
  'Dwarf Papillon',
  'English Angora',
  'English Lop',
  'English Spot',
  'Fauve de Bourgogne',
  'Flemish Giant',
  'Florida White',
  'French Angora',
  'French Lop',
  'German Angora',
  'German Giant',
  'Giant Chinchilla',
  'Giant Papillon',
  'Harlequin',
  'Havana',
  'Himalayan',
  'Hulstlander',
  'Hungarian Giant',
  'Jersey Wooly',
  'Lilac',
  'Lionhead',
  'Meissner Lop',
  'Mini Lop',
  'Mini Rex',
  'Mini Satin',
  'Miniature Cashmere Lop',
  'Miniature Lion Lop',
  'Miniature Rex',
  'Miniature Silver Fox',
  'Netherland Dwarf',
  'New Zealand',
  'New Zealand Red',
  'New Zealand White',
  'Palomino',
  'Papillon',
  'Polish',
  'Rex',
  'Rhinelander',
  'Russian',
  'Sable Marten',
  'Sallander',
  'Satin',
  'Satin Angora',
  'Satin Mini Lop',
  'Siberian',
  'Silver',
  'Silver Fox',
  'Silver Marten',
  'Standard Chinchilla',
  'Sussex',
  'Swiss Fox',
  'Tan',
  'Thrianta',
  'Vienna Blue',
  'Vienna White',
  'Zemplin',
  'Zika',
  'Zika Blue',
  'Zika Red',
  'Zika White',
  'Zika Yellow',
  'Zika Black',
  'Zika Gray',
  'Zika Chinchilla',
  'Zika Silver',
  'Zika Gold',
  'Zika Cream',
  'Zika Chocolate',
  'Zika Orange',
];