final List<String> razzeRagni = [
  'Brachypelma smithi (Tarantola Messicana a Ginocchia Rosse)',
  'Brachypelma hamorii',
  'Brachypelma albopilosum (Tarantola Riccia)',
  'Brachypelma boehmei (Tarantola a Ginocchia di Fuoco)',
  'Brachypelma emilia (Tarantola dalle Zampe Rosse)',
  'Grammostola rosea (Tarantola Rosa Cilena)',
  'Grammostola pulchripes (Tarantola a Ginocchia Dorate)',
  'Grammostola pulchra (Tarantola Nera Brasiliana)',
  'Aphonopelma seemanni (Tarantola a Strisce Bianche)',
  'Avicularia avicularia (Tarantola Rosa del Brasile)',
  'Avicularia versicolor (Tarantola Arcobaleno dei Caraibi)',
  'Poecilotheria regalis (Tarantola Ornamentale Indiana)',
  'Poecilotheria metallica (Tarantola Blu di Gooty)',
  'Lasiodora parahybana (Tarantola Rosa del Brasile Gigante)',
  'Lasiodora klugi',
  'Nhandu chromatus',
  'Nhandu coloratovillosus',
  'Psalmopoeus irminia (Tarantola Tigre Venezolana)',
  'Psalmopoeus cambridgei',
  'Haplopelma lividum (Tarantola Cobalto Blu)',
  'Haplopelma albostriatum (Tarantola Zebrata)',
  'Chilobrachys fimbriatus',
  'Cyriopagopus lividus',
  'Cyriocosmus elegans',
  'Monocentropus balfouri (Tarantola Socotra)',
  'Pterinochilus murinus (Tarantola OBT – Orange Baboon)',
  'Heteroscodra maculata (Tarantola Ornamental Baboon)',
  'Ceratogyrus darlingi (Tarantola Cornuta)',
  'Ceratogyrus marshalli',
  'Davus pentaloris',
  'Euathlus sp. Red',
  'Caribena versicolor',
  'Thrixopelma ockerti',
  'Xenesthis immanis',
  'Phormictopus cancerides',
  'Pamphobeteus antinous',
  'Pamphobeteus nigricolor',
  'Pamphobeteus platyomma',
  'Hapalopus sp. Colombia (Pumpkin Patch)',
  'Acanthoscurria geniculata (Tarantola a Ginocchia Bianche)',
  'Acanthoscurria chacoana',
  'Sericopelma rubronitens',
  'Cyclosternum fasciatum',
  'Tapinauchenius violaceus',
  'Tapinauchenius gigas',
  'Ephebopus murinus (Tarantola Squelette)',
  'Ephebopus cyanognathus',
  'Hapalopus formosus',
  'Neoholothele incei',
];