final List<String> razzeSerpenti = [
  'Pitone Reale (Python regius)',
  'Pitone delle Rocce Africano',
  'Pitone delle Rocce Indiano',
  'Pitone Reticolato',
  'Pitone Verde Arboricolo',
  'Pitone di Birmania',
  'Boa Constrictor',
  'Boa Arcobaleno (Epicrates cenchria)',
  'Anaconda Verde',
  'Anaconda Gialla',
  'Serpente del Latte (Lampropeltis triangulum)',
  'Serpente Reale della California',
  'Serpente del Mais (Pantherophis guttatus)',
  'Serpente Reale Scarlatto',
  'Serpente Reale Messicano',
  'Serpente Reale del Deserto',
  'Serpente del Grano',
  'Serpente Nero dei Ratti',
  'Serpente del Re del Deserto',
  'Serpente del Re della Florida',
  'Serpente del Re di Sonora',
  'Serpente del Re di Montagna',
  'Serpente del Re di California Albino',
  'Serpente del Re di Brooks',
  'Serpente del Re di Arizona',
  'Serpente del Re di Florida Latte',
  'Serpente del Re di Pueblan',
  'Serpente del Re di Sinaloan',
  'Serpente del Re di Honduran',
  'Serpente del Re di Nelson',
  'Serpente del Re di Thayer',
  'Serpente del Re di Ruthven',
  'Serpente del Re di Durango',
  'Serpente del Re di Pacifico',
  'Serpente del Re di Baja California',
  'Serpente del Re di San Diego',
  'Serpente del Re di California Nero',
  'Serpente del Re di California Banana',
  'Serpente del Re di California Striato',
  'Serpente del Re di California Pezzato',
  'Serpente del Re di California Lavanda',
  'Serpente del Re di California Albino Striato',
  'Serpente del Re di California Hypo',
  'Serpente del Re di California Ghost',
  'Serpente del Re di California Snow',
  'Serpente del Re di California Tangerine',
  'Serpente del Re di California Mosaic',
  'Serpente del Re di California High White',
  'Serpente del Re di California Jungle',
  'Serpente del Re di California Granite',
  'Serpente del Re di California Reverse Stripe',
];