final List<String> razzeTartarughe = [
  'Testuggine di Hermann',
  'Testuggine Greca',
  'Testuggine Marginata',
  'Testuggine delle Steppe (Tartaruga Russa)',
  'Testuggine Egiziana',
  'Testuggine Leopardina',
  'Testuggine Stellata Indiana',
  'Testuggine Africana Fianchi Seghettati',
  'Testuggine del Deserto',
  'Testuggine del Capo',
  'Testuggine del Gopher',
  'Testuggine di Aldabra',
  'Testuggine Gigante delle Seychelles',
  'Testuggine delle Galápagos',
  'Tartaruga dalle Orecchie Rosse (Trachemys scripta elegans)',
  'Tartaruga dalle Orecchie Gialle',
  'Tartaruga del Fango (Kinosternon)',
  'Tartaruga Moschata Comune',
  'Tartaruga Dipinta',
  'Tartaruga a Guscio Morbido (Apalone spinifera)',
  'Tartaruga Alligatore (Macrochelys temminckii)',
  'Tartaruga Maculata (Clemmys guttata)',
  'Tartaruga di Cuvier',
  'Tartaruga di Reeves',
  'Tartaruga di Florida (Pseudemys nelsoni)',
  'Tartaruga di Map (Graptemys)',
  'Tartaruga di Fiume Mary (Elusor macrurus)',
  'Tartaruga di Sternotherus odoratus',
  'Tartaruga di Cuora amboinensis',
  'Tartaruga di Matamata',
  'Tartaruga di Box (Terrapene carolina)',
  'Tartaruga di Bosque',
  'Tartaruga di Pancake (Malacochersus tornieri)',
  'Tartaruga di Foresta Africana',
  'Tartaruga di Ruggine',
  'Tartaruga di Cuora flavomarginata',
  'Tartaruga di Cuora trifasciata',
  'Tartaruga di Cuora galbinifrons',
  'Tartaruga di Cuora mouhotii',
  'Tartaruga di Cuora picturata',
  'Tartaruga di Cuora zhoui',
  'Tartaruga di Cuora bourreti',
  'Tartaruga di Cuora pani',
  'Tartaruga di Cuora aurocapitata',
  'Tartaruga di Cuora mccordi',
  'Tartaruga di Cuora yunnanensis',
  'Tartaruga di Cuora amboinensis kamaroma',
  'Tartaruga di Cuora amboinensis couro',
];