// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_SECURE_FIREBASE_API_KEY',
    appId: '1:569543725876:web:08a58aacd0d0a18d8acb61',
    messagingSenderId: '569543725876',
    projectId: 'petping-39e1a',
    authDomain: 'petping-39e1a.firebaseapp.com',
    storageBucket: 'petping-39e1a.firebasestorage.app',
    measurementId: 'G-SXK1XCWGGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_SECURE_FIREBASE_API_KEY',
    appId: '1:569543725876:android:a60a24ca2b2773818acb61',
    messagingSenderId: '569543725876',
    projectId: 'petping-39e1a',
    storageBucket: 'petping-39e1a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_SECURE_FIREBASE_API_KEY',
    appId: '1:569543725876:ios:1378017d91dca1998acb61',
    messagingSenderId: '569543725876',
    projectId: 'petping-39e1a',
    storageBucket: 'petping-39e1a.firebasestorage.app',
    iosBundleId: 'com.petping.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_SECURE_FIREBASE_API_KEY',
    appId: '1:569543725876:ios:1378017d91dca1998acb61',
    messagingSenderId: '569543725876',
    projectId: 'petping-39e1a',
    storageBucket: 'petping-39e1a.firebasestorage.app',
    iosBundleId: 'com.petping.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_SECURE_FIREBASE_API_KEY',
    appId: '1:569543725876:web:3079905cfd18b0308acb61',
    messagingSenderId: '569543725876',
    projectId: 'petping-39e1a',
    authDomain: 'petping-39e1a.firebaseapp.com',
    storageBucket: 'petping-39e1a.firebasestorage.app',
    measurementId: 'G-PTZHPMLKW2',
  );
}
